name: Publish PowerShell Module

on:
  release:
    types: [created]

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        env:
          NUGETAPIKEY: ${{ secrets.NUGETAPIKEY }}
        shell: pwsh
        run: |
          Publish-Module -Path '.\PSPMP' -NuGetApiKey $env:NUGET_KEY -Verbose
